### ISSUE TITLE
Biobank explorer not working on IE10, IE11 and Edge

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis-app-biobank-explorer#80]
### How to Reproduce
Go to directory.bbmri-eric.eu

### Expected behavior
See biobanks

### Observed behavior
No biobanks are shown, errors in console:

## Edge
```
SCRIPT438: SCRIPT438: Object doesn't support property or method 'validate'
jquery-3.3.1.min.js (2,31040)
```

## IE10 +11
```
Unhandled promise rejection TypeError: Object doesn't support property or method 'flatMap'
```
Other browsers have also console errors:
## Chrome
```
jquery-3.3.1.min.js?hFuaYA:2 Uncaught TypeError: form.validate is not a function
    at HTMLDocument.<anonymous> (biobankexplorer:170)
    at l (jquery-3.3.1.min.js?hFuaYA:2)
    at c (jquery-3.3.1.min.js?hFuaYA:2)
(anonymous) @ biobankexplorer:170
l @ jquery-3.3.1.min.js?hFuaYA:2
c @ jquery-3.3.1.min.js?hFuaYA:2
setTimeout (async)
w.readyException @ jquery-3.3.1.min.js?hFuaYA:2
(anonymous) @ jquery-3.3.1.min.js?hFuaYA:2
l @ jquery-3.3.1.min.js?hFuaYA:2
c @ jquery-3.3.1.min.js?hFuaYA:2
setTimeout (async)
(anonymous) @ jquery-3.3.1.min.js?hFuaYA:2
u @ jquery-3.3.1.min.js?hFuaYA:2
fireWith @ jquery-3.3.1.min.js?hFuaYA:2
fire @ jquery-3.3.1.min.js?hFuaYA:2
u @ jquery-3.3.1.min.js?hFuaYA:2
fireWith @ jquery-3.3.1.min.js?hFuaYA:2
c @ jquery-3.3.1.min.js?hFuaYA:2
setTimeout (async)
(anonymous) @ jquery-3.3.1.min.js?hFuaYA:2
u @ jquery-3.3.1.min.js?hFuaYA:2
fireWith @ jquery-3.3.1.min.js?hFuaYA:2
fire @ jquery-3.3.1.min.js?hFuaYA:2
u @ jquery-3.3.1.min.js?hFuaYA:2
fireWith @ jquery-3.3.1.min.js?hFuaYA:2
ready @ jquery-3.3.1.min.js?hFuaYA:2
_ @ jquery-3.3.1.min.js?hFuaYA:2
port.js:30 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at chrome-extension://jeoacafpbcihiomhlakheieifhpjdfeo/scripts/vendor/port/port.js:30:48
    at chrome-extension://jeoacafpbcihiomhlakheieifhpjdfeo/scripts/vendor/port/port.js:603:3
```
## Firefox
```
TypeError: form.validate is not a function[Learn More]
```

## Safari
```
TypeError: form.validate is not a function. (In 'form.validate()', 'form.validate' is undefined)
(anonymous function) — jquery-3.3.1.min.js:1388
Selected Element
<div class="col-md-9">…</div>

```

**Comment by fdlk** [comment]
The culprit is the second error:

>Unhandled promise rejection TypeError: De eigenschap of methode flatMap wordt niet ondersteund door dit object

**Comment by fdlk** [comment]
Fixed in https://github.com/molgenis/molgenis/releases/tag/molgenis-7.2.14
